
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adewale
 */
public class reg extends javax.swing.JFrame {

    /**
     * Creates new form reg
     */
    Utilities utl = new Utilities();
    public reg() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Child Abuse Registration Page");
        Random rand = new Random();
        int rnd = rand.nextInt(9999)+1;
        lblid.setText(String.valueOf(rnd));
        utl.connect();
        cbogen.removeAllItems();
        cbogen.addItem("--SELECT--");
        cbogen.addItem("MALE");
         cbogen.addItem("FEMALE");
         cbogender.removeAllItems();
         cbogender.addItem("--SELECT--");
         cbogender.addItem("MALE");
         cbogender.addItem("FEMALE");
        txtd.setText(utl.curdate());
        cbosit.removeAllItems();
        cbosit.addItem("--SELECT--");
        cbosit.addItem("Rape");
        cbosit.addItem("Unconcious");
        cbosit.addItem("Maltreated");
        cbosit.addItem("Child Trafficking");
        cbosit.addItem("Beating");
        txtd.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtissue = new javax.swing.JTextArea();
        txtd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbosit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbogen = new javax.swing.JComboBox<>();
        txtphn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbogender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        txtname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtagge = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 2, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("CHILD ABUSE INFORMATION SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 10, 520, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTER'S DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel2.setLayout(null);

        lblid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(lblid);
        lblid.setBounds(480, 50, 110, 30);

        txtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        jPanel2.add(txtn);
        txtn.setBounds(10, 130, 260, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("**PHONENUMBER**");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 210, 130, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("FILE NUMBER:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 50, 130, 30);

        txtaddr.setColumns(20);
        txtaddr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtaddr.setRows(5);
        jScrollPane1.setViewportView(txtaddr);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(280, 130, 210, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("**GENDER**");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(760, 110, 100, 17);

        txtissue.setColumns(20);
        txtissue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtissue.setRows(5);
        jScrollPane2.setViewportView(txtissue);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(510, 130, 210, 60);

        txtd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdActionPerformed(evt);
            }
        });
        jPanel2.add(txtd);
        txtd.setBounds(490, 230, 250, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("**ADDRESS**");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(330, 110, 100, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("**ISSUE**");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(570, 110, 70, 17);

        cbosit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbosit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbosit);
        cbosit.setBounds(300, 230, 170, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("**NAME**");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(120, 110, 70, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("**SITUATION**");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(340, 210, 110, 17);

        cbogen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbogen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbogen);
        cbogen.setBounds(730, 130, 160, 30);

        txtphn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnActionPerformed(evt);
            }
        });
        jPanel2.add(txtphn);
        txtphn.setBounds(20, 230, 250, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("**DATE/TIME**");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(560, 210, 110, 17);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("**AGE**");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(800, 210, 60, 17);

        txtage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtage);
        txtage.setBounds(760, 230, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 930, 280);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VICTIM DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("**ADDRESS**");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(330, 70, 100, 17);

        cbogender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbogender);
        cbogender.setBounds(510, 100, 160, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("**NAME**");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(120, 70, 70, 17);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("**GENDER**");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(540, 80, 100, 17);

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane3.setViewportView(txtaddress);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(280, 90, 210, 60);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtname);
        txtname.setBounds(10, 90, 260, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("**AGE**");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(730, 80, 60, 17);

        txtagge.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtagge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtagge);
        txtagge.setBounds(680, 100, 160, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 340, 930, 170);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 550, 180, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 550, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void txtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdActionPerformed

    private void txtphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(txtn.getText().isEmpty()||txtaddr.getText().isEmpty()||txtissue.getText().isEmpty()||cbogen.getSelectedIndex()==0||txtphn.getText().isEmpty()||txtd.getText().isEmpty()||txtage.getText().isEmpty()||txtissue.getText().isEmpty()||txtn.getText().isEmpty()||txtaddress.getText().isEmpty()||txtagge.getText().isEmpty()||cbogender.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(this, "Please Supply a vital Details");
       return;
       } 
      utl.connect();
       try{
         String sql = "insert into new_record values('"+lblid.getText()+"','"+txtn.getText()+"','"+txtaddr.getText()+"','"+txtissue.getText()+"','"+cbogen.getSelectedItem().toString()+"','"+txtphn.getText()+"','"+cbosit.getSelectedItem().toString()+"','"+txtd.getText()+"','"+txtage.getText()+"','"+txtname.getText()+"','"+txtaddress.getText()+"','"+cbogender.getSelectedItem().toString()+"','"+txtagge.getText()+"')";
         utl.st.executeUpdate(sql);
         JOptionPane.showMessageDialog(this, "Data Successfully Saved");
         Random rand = new Random();
        int rnd = rand.nextInt(9999)+1;
        lblid.setText(String.valueOf(rnd));
        txtd.setText(utl.curdate());
        txtn.setText("");
        txtaddr.setText("");
        txtissue.setText("");
        cbogen.setSelectedItem("--SELECT--");
        txtphn.setText("");
        cbosit.setSelectedItem("--SELECT--");
        txtage.setText("");
        txtname.setText("");
        txtaddress.setText("");
       cbogender.setSelectedItem("--SELECT--");
       txtagge.setText("--SELECT--");
       }catch(Exception e){
       System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbogen;
    private javax.swing.JComboBox<String> cbogender;
    private javax.swing.JComboBox<String> cbosit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextArea txtaddr;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtagge;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextArea txtissue;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
