
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adewale
 */
public class view_details extends javax.swing.JFrame {

    /**
     * Creates new form view_details
     */
    Utilities utl = new Utilities();
    public view_details() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Edit/Update");
        setResizable(false);
        utl.connect();
        lble.setBackground(Color.red);
        lblf.setText("No Record Found");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtissue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lble = new javax.swing.JLabel();
        lblf = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtsitua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtag = new javax.swing.JTextField();
        txtgen = new javax.swing.JTextField();
        txtaddr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTER'S DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel4.setLayout(null);

        lblid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel4.add(lblid);
        lblid.setBounds(450, 160, 100, 30);

        txtissue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtissue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtissue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissueActionPerformed(evt);
            }
        });
        jPanel4.add(txtissue);
        txtissue.setBounds(550, 130, 280, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("**PHONENUMBER**");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(80, 190, 130, 20);

        lble.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lble.setForeground(new java.awt.Color(0, 51, 153));
        lble.setOpaque(true);
        jPanel4.add(lble);
        lble.setBounds(650, 50, 80, 30);

        lblf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblf.setForeground(new java.awt.Color(0, 0, 204));
        jPanel4.add(lblf);
        lblf.setBounds(760, 50, 170, 30);

        txtdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        jPanel4.add(txtdate);
        txtdate.setBounds(540, 210, 240, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("**ADDRESS**");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(330, 110, 100, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("**ISSUE**");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(660, 110, 70, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("**NAME**");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(120, 110, 70, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("**SITUATION**");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(340, 190, 110, 20);

        txtsitua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtsitua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsitua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtsitua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsituaActionPerformed(evt);
            }
        });
        jPanel4.add(txtsitua);
        txtsitua.setBounds(270, 210, 250, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("**DATE/TIME**");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(600, 190, 110, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("**AGE**");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(830, 190, 60, 20);

        txtnname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtnname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnnameActionPerformed(evt);
            }
        });
        jPanel4.add(txtnname);
        txtnname.setBounds(20, 130, 240, 30);

        txtaddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel4.add(txtaddress);
        txtaddress.setBounds(290, 130, 250, 30);

        txtage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        jPanel4.add(txtage);
        txtage.setBounds(810, 210, 110, 30);

        txtphone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel4.add(txtphone);
        txtphone.setBounds(10, 210, 250, 30);

        txtgender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtgender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        jPanel4.add(txtgender);
        txtgender.setBounds(840, 130, 120, 30);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        jPanel4.add(txtid);
        txtid.setBounds(410, 50, 230, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("**GENDER**");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(840, 110, 100, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("ENTER REPORT ID:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(230, 50, 180, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 10, 970, 270);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VICTIM DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("**ADDRESS**");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(380, 70, 100, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("**NAME**");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(120, 70, 70, 17);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("**AGE**");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(70, 130, 60, 17);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel5.add(txtname);
        txtname.setBounds(10, 90, 240, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("**GENDER**");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(700, 60, 90, 17);

        txtag.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtag.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagActionPerformed(evt);
            }
        });
        jPanel5.add(txtag);
        txtag.setBounds(660, 80, 150, 30);

        txtgen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtgen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenActionPerformed(evt);
            }
        });
        jPanel5.add(txtgen);
        txtgen.setBounds(10, 150, 170, 30);

        txtaddr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtaddr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 204)));
        txtaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddrActionPerformed(evt);
            }
        });
        jPanel5.add(txtaddr);
        txtaddr.setBounds(310, 90, 290, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 280, 960, 190);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(800, 480, 130, 40);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(340, 480, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(500, 480, 130, 40);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(650, 480, 130, 40);

        jTabbedPane1.addTab("Edit/Update", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jPanel3.setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ADDRESS", "GENDER", "AGE", "ISSUE", "DATE/TIME"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 960, 420);

        jButton6.setBackground(new java.awt.Color(0, 153, 51));
        jButton6.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("VIEW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(700, 500, 110, 40);

        jButton7.setBackground(new java.awt.Color(0, 153, 51));
        jButton7.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("PRINT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(820, 500, 110, 40);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Affected Child Information ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(350, 10, 360, 40);

        jTabbedPane1.addTab("View", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            String sql = "update new_record set nname = '"+txtnname.getText()+"',addr = '"+txtaddress.getText()+"',issue ='"+txtissue.getText()+"',ge ='"+txtgender.getText()+"',phn = '"+txtphone.getText()+"', sit = '"+txtsitua.getText()+"',age = '"+txtage.getText()+"', vname = '"+txtname.getText()+"',vaddr ='"+txtaddr.getText()+"',vgender ='"+txtag.getText()+"',vage ='"+txtgen.getText()+"'";
            utl.st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Data Successfull Updated");
            txtnname.setText("");
            txtaddress.setText("");
            txtissue.setText("");
            txtgender.setText("");
            txtphone.setText("");
            txtsitua.setText("");
            txtage.setText("");
            txtname.setText("");
            txtaddr.setText("");
            txtag.setText("");
            

        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtnname.setEditable(true);
        txtaddr.setEditable(true);
        txtissue.setEditable(true);
        txtgender.setEditable(true);
        txtphone.setEditable(true);
        txtsitua.setEditable(true);

        txtage.setEditable(true);
        txtname.setEditable(true);
        txtaddr.setEditable(true);
        txtag.setEditable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String sql = "delete from new_record where ID = '"+txtid.getText()+"'";
            utl.st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Data Successfully Deleted");
            txtnname.setText("");
            txtaddress.setText("");
            txtissue.setText("");
            txtgender.setText("");
            txtphone.setText("");
            txtsitua.setText("");
            txtage.setText("");
            txtname.setText("");
            txtaddr.setText("");
            txtag.setText("");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddrActionPerformed

    private void txtgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenActionPerformed

    private void txtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtagActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        try{
            ResultSet rs = utl.st.executeQuery("select nname,addr,issue,ge,phn,sit,curdate,age,vname,vaddr,vgender,vage from new_record where ID = '"+txtid.getText()+"'");

            if(rs.next()){
                txtnname.setText(rs.getString(1));
                txtaddr.setText(rs.getString(2));
                txtissue.setText(rs.getString(3));
                txtgender.setText(rs.getString(4));
                txtphone.setText(rs.getString(5));
                txtsitua.setText(rs.getString(6));
                txtdate.setText(rs.getString(7));
                txtage.setText(rs.getString(8));

                txtname.setText(rs.getString(9));
                txtaddr.setText(rs.getString(10));
                txtgen.setText(rs.getString(11));
                txtag.setText(rs.getString(12));
                lblf.setText("One Record Found");
                lble.setBackground(Color.green);
                txtnname.setEditable(false);
                txtaddr.setEditable(false);
                txtissue.setEditable(false);
                txtgender.setEditable(false);
                txtphone.setEditable(false);
                txtsitua.setEditable(false);
                txtdate.setEditable(false);
                txtage.setEditable(false);
                txtname.setEditable(false);
                txtaddr.setEditable(false);
                txtag.setEditable(false);

            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtidKeyReleased

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnnameActionPerformed

    private void txtsituaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsituaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsituaActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissueActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
          ResultSet rs = utl.st.executeQuery("select vname,vaddr,vgender,vage,issue,curdate from new_record");
          DefaultTableModel dft = (DefaultTableModel) tbl.getModel();
          dft.setRowCount(0);
          while(rs.next()){
              Object o[] = { rs.getString("vname"),rs.getString("vaddr"),rs.getString("vgender"),rs.getString("vage"),rs.getString("issue"),rs.getString("curdate")};
              dft.addRow(o);
              
          }
          tbl.setModel(dft);
          tbl.setShowGrid(true);
          tbl.setEnabled(false);
          tbl.setForeground(Color.white);
          tbl.setBackground(Color.blue);
          tbl.setRowHeight(24);
      
          tbl.setFont(new java.awt.Font("Tahoma", 1, 13));
          tbl.setCellSelectionEnabled(false); 
          
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       try{
           tbl.print();
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lble;
    private javax.swing.JLabel lblf;
    private javax.swing.JLabel lblid;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtag;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtgen;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtissue;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsitua;
    // End of variables declaration//GEN-END:variables
}
